// <auto-generated />
using CoffeShop.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CoffeShop.Migrations
{
    [DbContext(typeof(CoffeshopDbContext))]
    partial class CoffeshopDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.25")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("CoffeShop.Models.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Detail")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsTrendingProduct")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Detail = "Cà phê đen đậm đà truyền thống Việt Nam, pha phin thủ công.",
                            ImageUrl = "https://upload.wikimedia.org/wikipedia/commons/4/45/A_small_cup_of_coffee.JPG",
                            IsTrendingProduct = true,
                            Name = "Cà phê đen",
                            Price = 25000m
                        },
                        new
                        {
                            Id = 2,
                            Detail = "Cà phê phin kết hợp sữa đặc ngọt ngào, hương vị đặc trưng.",
                            ImageUrl = "https://upload.wikimedia.org/wikipedia/commons/4/45/A_small_cup_of_coffee.JPG",
                            IsTrendingProduct = true,
                            Name = "Cà phê sữa",
                            Price = 30000m
                        },
                        new
                        {
                            Id = 3,
                            Detail = "Cà phê sữa tỉ lệ sữa nhiều hơn, nhẹ nhàng và béo ngậy.",
                            ImageUrl = "https://upload.wikimedia.org/wikipedia/commons/4/45/A_small_cup_of_coffee.JPG",
                            IsTrendingProduct = false,
                            Name = "Bạc xỉu",
                            Price = 32000m
                        },
                        new
                        {
                            Id = 4,
                            Detail = "Espresso pha với sữa nóng đánh bọt mịn, phong cách Ý.",
                            ImageUrl = "https://upload.wikimedia.org/wikipedia/commons/4/45/A_small_cup_of_coffee.JPG",
                            IsTrendingProduct = true,
                            Name = "Cappuccino",
                            Price = 55000m
                        },
                        new
                        {
                            Id = 5,
                            Detail = "Espresso với lượng lớn sữa nóng, vị nhẹ và thơm.",
                            ImageUrl = "https://upload.wikimedia.org/wikipedia/commons/4/45/A_small_cup_of_coffee.JPG",
                            IsTrendingProduct = false,
                            Name = "Latte",
                            Price = 60000m
                        },
                        new
                        {
                            Id = 6,
                            Detail = "Cà phê ủ lạnh 12 giờ, vị đậm mượt mà không chua.",
                            ImageUrl = "https://upload.wikimedia.org/wikipedia/commons/4/45/A_small_cup_of_coffee.JPG",
                            IsTrendingProduct = true,
                            Name = "Cold Brew",
                            Price = 65000m
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
